/**
 * ReturnFlow - Seed Data & Initial Schema
 * Retail Returns, Refunds & Claims Exception Management
 */

const SEED_DATA = {
  users: [
    {
      id: 'usr_1',
      username: 'cs.agent',
      password: 'demo123',
      name: 'Pooja Verma',
      role: 'Customer Service',
      roleKey: 'customer_service',
      title: 'Senior Customer Support Specialist',
      email: 'pooja.verma@retailcorp.in',
      avatar: 'PV',
      permissions: ['create_return', 'view_cases', 'run_ai_review', 'submit_exception', 'view_notifications', 'view_profile']
    },
    {
      id: 'usr_2',
      username: 'returns.manager',
      password: 'demo123',
      name: 'Vikramaditya Sen',
      role: 'Returns Manager',
      roleKey: 'returns_manager',
      title: 'Head of Reverse Logistics & Exceptions',
      email: 'vikram.sen@retailcorp.in',
      avatar: 'VS',
      permissions: ['create_return', 'view_cases', 'view_exceptions', 'approve_refund', 'reject_refund', 'override_ai', 'escalate_case', 'view_analytics', 'view_notifications', 'view_activity_log', 'view_profile']
    },
    {
      id: 'usr_3',
      username: 'finance.approver',
      password: 'demo123',
      name: 'Ananya Deshmukh',
      role: 'Finance',
      roleKey: 'finance',
      title: 'Lead Financial Controller (Disbursements)',
      email: 'ananya.d@retailcorp.in',
      avatar: 'AD',
      permissions: ['view_cases', 'view_finance', 'approve_settlement', 'reject_settlement', 'view_analytics', 'view_notifications', 'view_activity_log', 'view_profile']
    },
    {
      id: 'usr_4',
      username: 'vendor.manager',
      password: 'demo123',
      name: 'Rajesh Nair',
      role: 'Vendor Management',
      roleKey: 'vendor_manager',
      title: 'Director of Supplier Quality & Recoveries',
      email: 'rajesh.nair@retailcorp.in',
      avatar: 'RN',
      permissions: ['view_cases', 'view_vendor_claims', 'raise_claim', 'accept_claim', 'dispute_claim', 'view_analytics', 'view_notifications', 'view_activity_log', 'view_profile']
    },
    {
      id: 'usr_5',
      username: 'warehouse.manager',
      password: 'demo123',
      name: 'Gurpreet Singh',
      role: 'Warehouse',
      roleKey: 'warehouse',
      title: 'Central Fulfillment & WMS Lead',
      email: 'gurpreet.s@retailcorp.in',
      avatar: 'GS',
      permissions: ['view_cases', 'view_disposition', 'update_disposition', 'view_notifications', 'view_activity_log', 'view_profile']
    },
    {
      id: 'usr_6',
      username: 'admin',
      password: 'admin123',
      name: 'System Administrator',
      role: 'Administrator',
      roleKey: 'admin',
      title: 'Enterprise Platform Administrator',
      email: 'admin@retailcorp.in',
      avatar: 'SA',
      permissions: ['all']
    }
  ],

  settings: {
    autoApproveThreshold: 5000,
    highValueThreshold: 10000,
    policyWindowDays: 30,
    autoDecisionTargetPct: 70,
    currencySymbol: '₹',
    slaStandardHours: 24,
    slaHighPriorityHours: 4
  },

  cases: [
    {
      id: 'RET-1048',
      orderId: 'ORD-98241',
      customer: 'Priya Sharma',
      customerEmail: 'priya.sharma@example.com',
      customerPhone: '+91 98201 44821',
      product: 'Smart Air Fryer Pro 5.5L',
      category: 'Home & Kitchen',
      purchaseValue: 4899,
      purchaseDate: '2026-09-29',
      daysSincePurchase: 9,
      returnReason: 'Defective Product',
      condition: 'Opened',
      channel: 'Website',
      paymentMethod: 'UPI (GooglePay)',
      vendor: 'Nova Appliances Ltd',
      vendorSku: 'NOVA-AF-550',
      customerNotes: 'Heating coil stopped working after 3 days. LED display flickers intermittently.',
      evidenceCount: 2,
      evidenceList: [
        { type: 'image', name: 'error_code_e3.jpg', size: '2.1 MB', note: 'Error E3 displayed on digital control panel' },
        { type: 'pdf', name: 'tax_invoice_98241.pdf', size: '480 KB', note: 'Original retail purchase invoice' }
      ],
      riskLevel: 'Low',
      fraudScore: 8,
      aiAssessment: {
        eligibility: 'Eligible (Within 30d Window)',
        riskLevel: 'Low',
        fraudRisk: 'Low (Score: 8/100)',
        suggestedDecision: 'AUTO APPROVE',
        confidence: 96,
        reasoning: 'Within policy window (9 days), value ₹4,899 is below ₹5,000 auto-threshold, error photo matches manufacturer defect bulletin, customer account age is 3.4 years with 0 previous fraud flags.',
        requiredEvidence: 'Photo of error code verified via OCR pattern matching.',
        recommendedAction: 'Auto-approve refund to original UPI account; route claim to Nova Appliances for 100% manufacturer warranty recovery.'
      },
      status: 'Refund Approved',
      assignedTo: 'Auto Decision Engine',
      slaHoursLeft: 22,
      createdAt: '2026-10-07T09:30:00.000Z',
      updatedAt: '2026-10-07T09:32:00.000Z',
      createdBy: 'cs.agent'
    },
    {
      id: 'RET-1045',
      orderId: 'ORD-98177',
      customer: 'Rahul Kumar',
      customerEmail: 'rahul.k99@example.com',
      customerPhone: '+91 98112 55902',
      product: 'Premium Noise-Cancelling Headphones Pro',
      category: 'Electronics',
      purchaseValue: 14999,
      purchaseDate: '2026-09-25',
      daysSincePurchase: 13,
      returnReason: 'Damaged Item',
      condition: 'Damaged',
      channel: 'Mobile App',
      paymentMethod: 'Credit Card (HDFC)',
      vendor: 'Acoustic Sound Labs',
      vendorSku: 'ASL-NC900-BLK',
      customerNotes: 'Right headband hinge arrived snapped inside the retail packaging.',
      evidenceCount: 3,
      evidenceList: [
        { type: 'image', name: 'broken_hinge_macro.jpg', size: '3.4 MB', note: 'Close-up of physical fracture on right hinge' },
        { type: 'image', name: 'courier_box_crushed.jpg', size: '2.8 MB', note: 'External transit carton crushed on corner' },
        { type: 'pdf', name: 'courier_pod.pdf', size: '320 KB', note: 'Delivery acknowledgement with remark "box torn"' }
      ],
      riskLevel: 'Medium',
      fraudScore: 32,
      aiAssessment: {
        eligibility: 'Eligible with Human Review',
        riskLevel: 'Medium',
        fraudRisk: 'Moderate (Score: 32/100)',
        suggestedDecision: 'MANUAL REVIEW',
        confidence: 84,
        reasoning: 'High value ₹14,999 exceeds auto-approve ceiling (₹10,000 threshold). Damage pattern aligns with courier transit crush evidence. Inspection required before final settlement.',
        requiredEvidence: 'Courier POD damage remark and physical unit serial number confirmation.',
        recommendedAction: 'Returns Manager review required. If approved, issue RMA with courier carrier damage claim.'
      },
      status: 'Exception',
      assignedTo: 'Vikramaditya Sen',
      slaHoursLeft: 3,
      createdAt: '2026-10-07T11:15:00.000Z',
      updatedAt: '2026-10-07T11:20:00.000Z',
      createdBy: 'cs.agent'
    },
    {
      id: 'RET-1042',
      orderId: 'ORD-98031',
      customer: 'Ananya Rao',
      customerEmail: 'ananya.rao.tech@example.com',
      customerPhone: '+91 97401 22910',
      product: 'UltraSlim 5G Flagship Smartphone 256GB',
      category: 'Electronics',
      purchaseValue: 42999,
      purchaseDate: '2026-09-02',
      daysSincePurchase: 36,
      returnReason: 'Changed Mind',
      condition: 'Opened',
      channel: 'Website',
      paymentMethod: 'Net Banking (ICICI)',
      vendor: 'Apex Mobile Distro',
      vendorSku: 'APX-S24-TIT',
      customerNotes: 'Did not like the camera UI. Want full cash refund.',
      evidenceCount: 1,
      evidenceList: [
        { type: 'image', name: 'phone_box.jpg', size: '1.4 MB', note: 'Opened retail box' }
      ],
      riskLevel: 'High',
      fraudScore: 82,
      aiAssessment: {
        eligibility: 'Policy Violation (Return Window Exceeded)',
        riskLevel: 'High',
        fraudRisk: 'High (Score: 82/100)',
        suggestedDecision: 'REJECT / ESCALATE',
        confidence: 98,
        reasoning: 'Return initiated on day 36 (exceeds mandatory 30-day policy). Changed mind is non-returnable on opened high-value smartphones under Category Policy Sec 4.2.',
        requiredEvidence: 'Manager approval required for exceptional brand goodwill concession.',
        recommendedAction: 'Route to Returns Manager for formal policy rejection or goodwill gift card exchange approval.'
      },
      status: 'Escalated',
      assignedTo: 'Vikramaditya Sen',
      slaHoursLeft: 1,
      createdAt: '2026-10-06T14:40:00.000Z',
      updatedAt: '2026-10-07T08:10:00.000Z',
      createdBy: 'cs.agent'
    },
    {
      id: 'RET-1039',
      orderId: 'ORD-97812',
      customer: 'Kiran Das',
      customerEmail: 'kiran.das88@example.com',
      customerPhone: '+91 99002 88123',
      product: 'Smart Fitness GPS Watch Series 5',
      category: 'Electronics',
      purchaseValue: 18999,
      purchaseDate: '2026-09-27',
      daysSincePurchase: 11,
      returnReason: 'Wrong Product',
      condition: 'Opened',
      channel: 'Website',
      paymentMethod: 'Credit Card (Axis)',
      vendor: 'Acoustic Sound Labs',
      vendorSku: 'ASL-WAT-S5',
      customerNotes: 'Customer states package contained cheap counterfeit plastic watch instead of titanium smartwatch.',
      evidenceCount: 2,
      evidenceList: [
        { type: 'image', name: 'received_item_photo.jpg', size: '2.5 MB', note: 'Customer photo of cheap generic device' },
        { type: 'image', name: 'security_seal.jpg', size: '1.9 MB', note: 'Tampered tamper-evident security tape' }
      ],
      riskLevel: 'High',
      fraudScore: 78,
      aiAssessment: {
        eligibility: 'High Risk / Suspected Switch Fraud',
        riskLevel: 'High',
        fraudRisk: 'High (Score: 78/100)',
        suggestedDecision: 'MANUAL INVESTIGATION',
        confidence: 91,
        reasoning: 'Weight discrepancy detected: Outbound WMS scale recorded 420g; customer carrier return weigh-in recorded 160g. Fraud risk engine flagged account address with 2 similar prior claims.',
        requiredEvidence: 'WMS packing CCTV footage and courier depot security scan.',
        recommendedAction: 'Freeze automatic refund. Assign to senior investigator for warehouse CCTV audit before decision.'
      },
      status: 'Exception',
      assignedTo: 'Vikramaditya Sen',
      slaHoursLeft: 2,
      createdAt: '2026-10-06T16:20:00.000Z',
      updatedAt: '2026-10-07T09:00:00.000Z',
      createdBy: 'cs.agent'
    },
    {
      id: 'RET-1035',
      orderId: 'ORD-97650',
      customer: 'Neha Jain',
      customerEmail: 'neha.jain.delhi@example.com',
      customerPhone: '+91 98105 11980',
      product: 'Handwoven Silk Festive Kurta Set',
      category: 'Apparel',
      purchaseValue: 3499,
      purchaseDate: '2026-10-01',
      daysSincePurchase: 7,
      returnReason: 'Size/Fit Issue',
      condition: 'New',
      channel: 'Website',
      paymentMethod: 'UPI (Paytm)',
      vendor: 'Vedic Threads Apparel',
      vendorSku: 'VTA-KUR-M',
      customerNotes: 'Size M runs slightly large. Requesting return and refund.',
      evidenceCount: 1,
      evidenceList: [
        { type: 'image', name: 'tag_intact.jpg', size: '1.1 MB', note: 'Original brand tags intact and attached' }
      ],
      riskLevel: 'Low',
      fraudScore: 4,
      aiAssessment: {
        eligibility: 'Fully Eligible',
        riskLevel: 'Low',
        fraudRisk: 'Low (Score: 4/100)',
        suggestedDecision: 'AUTO APPROVE',
        confidence: 99,
        reasoning: 'Within 30-day window, tags attached, value ₹3,499 below auto-threshold, flawless customer history (0 returns in past 12 months).',
        requiredEvidence: 'Tags attached photo confirmed.',
        recommendedAction: 'Auto-approve refund; generate warehouse return label with Restock tag.'
      },
      status: 'Settlement Approved',
      assignedTo: 'Auto Decision Engine',
      slaHoursLeft: 24,
      createdAt: '2026-10-05T10:00:00.000Z',
      updatedAt: '2026-10-07T10:30:00.000Z',
      createdBy: 'cs.agent'
    },
    {
      id: 'RET-1031',
      orderId: 'ORD-97422',
      customer: 'Aditya Bose',
      customerEmail: 'aditya.bose@example.com',
      customerPhone: '+91 98300 77412',
      product: 'Orthopedic Memory Foam Mattress Double',
      category: 'Home & Kitchen',
      purchaseValue: 16499,
      purchaseDate: '2026-09-18',
      daysSincePurchase: 20,
      returnReason: 'Defective Product',
      condition: 'Used',
      channel: 'Website',
      paymentMethod: 'Credit Card (SBI)',
      vendor: 'SleepWell Ergonomics',
      vendorSku: 'SWE-MAT-DBL',
      customerNotes: 'Uneven sinking on left zone after 2 weeks of normal use.',
      evidenceCount: 2,
      evidenceList: [
        { type: 'image', name: 'sag_measurement.jpg', size: '2.3 MB', note: 'Ruler measuring 4.5cm dip under flat bar' },
        { type: 'pdf', name: 'warranty_card.pdf', size: '510 KB', note: '10-Year Manufacturer Warranty Certificate' }
      ],
      riskLevel: 'Medium',
      fraudScore: 18,
      aiAssessment: {
        eligibility: 'Eligible under Vendor Warranty',
        riskLevel: 'Medium',
        fraudRisk: 'Low (Score: 18/100)',
        suggestedDecision: 'APPROVE + VENDOR RECOVERY',
        confidence: 92,
        reasoning: 'Physical measurement photo confirms manufacturing foam density failure covered under SleepWell vendor SLA clause 6.3.',
        requiredEvidence: 'Sag measurement photo and serial tag.',
        recommendedAction: 'Approve customer refund; issue 100% vendor chargeback claim VR-2038 to SleepWell.'
      },
      status: 'Refund Approved',
      assignedTo: 'Vikramaditya Sen',
      slaHoursLeft: 12,
      createdAt: '2026-10-04T12:00:00.000Z',
      updatedAt: '2026-10-07T08:00:00.000Z',
      createdBy: 'cs.agent'
    }
  ],

  exceptions: [
    {
      id: 'EXC-501',
      caseId: 'RET-1045',
      exceptionType: 'High Value Return & Transit Damage',
      customer: 'Rahul Kumar',
      orderValue: 14999,
      riskLevel: 'Medium',
      evidenceSummary: 'Carrier POD damage remark + crack photos',
      slaStatus: 'Action Required (3h left)',
      slaHoursRemaining: 3,
      owner: 'Vikramaditya Sen',
      status: 'In Review',
      createdAt: '2026-10-07T11:20:00.000Z'
    },
    {
      id: 'EXC-502',
      caseId: 'RET-1042',
      exceptionType: 'Policy Violation (Days > 30)',
      customer: 'Ananya Rao',
      orderValue: 42999,
      riskLevel: 'High',
      evidenceSummary: 'Late return (36d) + opened high-value phone',
      slaStatus: 'Critical SLA (1h left)',
      slaHoursRemaining: 1,
      owner: 'Vikramaditya Sen',
      status: 'Escalated to Manager',
      createdAt: '2026-10-06T14:40:00.000Z'
    },
    {
      id: 'EXC-503',
      caseId: 'RET-1039',
      exceptionType: 'Suspected Fraud / Weight Mismatch',
      customer: 'Kiran Das',
      orderValue: 18999,
      riskLevel: 'High',
      evidenceSummary: 'WMS scale delta: 420g vs 160g return package',
      slaStatus: 'Investigating (2h left)',
      slaHoursRemaining: 2,
      owner: 'Vikramaditya Sen',
      status: 'In Investigation',
      createdAt: '2026-10-06T16:20:00.000Z'
    }
  ],

  refunds: [
    {
      id: 'RF-2048',
      caseId: 'RET-1048',
      customer: 'Priya Sharma',
      amount: 4899,
      originalAmount: 4899,
      paymentMethod: 'UPI (GooglePay / ICICI Gateway)',
      gatewayRef: 'UPI-REF-992019482',
      status: 'Pending Finance Settlement',
      approvedBy: 'Auto Decision Engine / Returns Manager',
      approvedAt: '2026-10-07T09:32:00.000Z',
      financeApprover: null,
      financeSettledAt: null,
      notes: 'Auto-approved within policy. Awaiting Finance daily batch settlement.'
    },
    {
      id: 'RF-2035',
      caseId: 'RET-1035',
      customer: 'Neha Jain',
      amount: 3499,
      originalAmount: 3499,
      paymentMethod: 'UPI (Paytm Payments Bank)',
      gatewayRef: 'UPI-PAYTM-88129031',
      status: 'Settlement Approved',
      approvedBy: 'Auto Decision Engine',
      approvedAt: '2026-10-05T10:05:00.000Z',
      financeApprover: 'Ananya Deshmukh',
      financeSettledAt: '2026-10-06T11:00:00.000Z',
      notes: 'Settlement processed and credited to customer account.'
    },
    {
      id: 'RF-2031',
      caseId: 'RET-1031',
      customer: 'Aditya Bose',
      amount: 16499,
      originalAmount: 16499,
      paymentMethod: 'Credit Card (SBI Card Gateway)',
      gatewayRef: 'CC-SBI-77219904',
      status: 'Pending Finance Settlement',
      approvedBy: 'Vikramaditya Sen',
      approvedAt: '2026-10-07T08:00:00.000Z',
      financeApprover: null,
      financeSettledAt: null,
      notes: 'Manager approved exception. High-value refund requires secondary Finance sign-off.'
    }
  ],

  vendorClaims: [
    {
      id: 'VR-2041',
      caseId: 'RET-1048',
      vendor: 'Nova Appliances Ltd',
      product: 'Smart Air Fryer Pro 5.5L',
      reason: 'Manufacturing Defect (Heating Coil Failure)',
      claimType: 'Warranty Chargeback',
      recoveryAmount: 4899,
      claimedAmount: 4899,
      status: 'Claim Raised',
      evidenceSummary: 'Error code photo E3 + invoice',
      raisedBy: 'Rajesh Nair',
      raisedAt: '2026-10-07T09:40:00.000Z',
      vendorResponse: 'Awaiting vendor portal acknowledgment (SLA: 48h).',
      updatedAt: '2026-10-07T09:40:00.000Z'
    },
    {
      id: 'VR-2038',
      caseId: 'RET-1031',
      vendor: 'SleepWell Ergonomics',
      product: 'Orthopedic Memory Foam Mattress Double',
      reason: 'Premature Foam Sinking Defect',
      claimType: 'Supplier Quality SLA Penalty',
      recoveryAmount: 16499,
      claimedAmount: 16499,
      status: 'Disputed',
      evidenceSummary: 'Sag measurement photo (4.5cm dip) + warranty card',
      raisedBy: 'Rajesh Nair',
      raisedAt: '2026-10-05T14:15:00.000Z',
      vendorResponse: 'Vendor claims mattress placed on unapproved slatted base. Counter-evidence requested.',
      updatedAt: '2026-10-06T16:00:00.000Z'
    },
    {
      id: 'VR-2022',
      caseId: 'RET-1022',
      vendor: 'Acoustic Sound Labs',
      product: 'Studio Bluetooth Speaker Max',
      reason: 'Defective Bluetooth Chipset Batch #B88',
      claimType: 'Recall Recovery',
      recoveryAmount: 24500,
      claimedAmount: 24500,
      status: 'Accepted',
      evidenceSummary: 'Serial number verified against Vendor Recall Notice #2026-09',
      raisedBy: 'Rajesh Nair',
      raisedAt: '2026-09-28T10:00:00.000Z',
      vendorResponse: 'Claim fully accepted. Credit note CN-ASL-9981 issued for next inventory invoice.',
      updatedAt: '2026-10-02T15:30:00.000Z'
    }
  ],

  dispositions: [
    {
      id: 'DSP-3048',
      caseId: 'RET-1048',
      product: 'Smart Air Fryer Pro 5.5L',
      condition: 'Defective (Electrical)',
      recommendedDisposition: 'Refurbish',
      selectedDisposition: 'Refurbish',
      warehouseLocation: 'Bengaluru Fulfillment Center (BLR-02) - Zone D-14',
      status: 'Pending Inspection',
      inventoryImpact: '+1 Refurbishment Queue (SKU-AF550-R)',
      handledBy: 'Gurpreet Singh',
      notes: 'Item in transit to Central WMS. Scheduled for bench repair inspection.',
      updatedAt: '2026-10-07T09:35:00.000Z'
    },
    {
      id: 'DSP-3035',
      caseId: 'RET-1035',
      product: 'Handwoven Silk Festive Kurta Set',
      condition: 'New (Tags Attached)',
      recommendedDisposition: 'Restock',
      selectedDisposition: 'Restock',
      warehouseLocation: 'Delhi NCR Hub (DEL-01) - Bin A-08',
      status: 'Inventory Updated',
      inventoryImpact: '+1 Active Saleable Stock (SKU-VTA-KUR-M)',
      handledBy: 'Gurpreet Singh',
      notes: 'Physical check passed. Steam pressed, bagged and restocked to available web inventory.',
      updatedAt: '2026-10-06T15:20:00.000Z'
    },
    {
      id: 'DSP-3028',
      caseId: 'RET-1028',
      product: 'Ceramic Dinner Set 24-Piece',
      condition: 'Damaged (6 Plates Shattered)',
      recommendedDisposition: 'Liquidate',
      selectedDisposition: 'Liquidate',
      warehouseLocation: 'Mumbai Logistics Hub (BOM-03) - Salvage Cage 2',
      status: 'Inventory Updated',
      inventoryImpact: 'Salvage Batch #LB-992 (Expected Realization ₹650)',
      handledBy: 'Gurpreet Singh',
      notes: 'Broken items safely scrapped. Remaining 18 intact items routed to B2B bulk liquidation auction.',
      updatedAt: '2026-10-05T11:45:00.000Z'
    }
  ],

  notifications: [
    {
      id: 'NOTIF-101',
      title: 'High-Value Exception Assigned',
      message: 'Case RET-1045 (₹14,999 Headphones) requires manual review due to damage evidence.',
      type: 'warning',
      timestamp: '2026-10-07T11:20:00.000Z',
      read: false,
      roleTarget: 'Returns Manager',
      linkPage: 'exceptions',
      linkId: 'RET-1045'
    },
    {
      id: 'NOTIF-102',
      title: 'Refund Awaiting Finance Approval',
      message: 'Manager approved refund RF-2031 (₹16,499) for Case RET-1031. Action required.',
      type: 'info',
      timestamp: '2026-10-07T08:05:00.000Z',
      read: false,
      roleTarget: 'Finance',
      linkPage: 'finance',
      linkId: 'RF-2031'
    },
    {
      id: 'NOTIF-103',
      title: 'Vendor Dispute Received',
      message: 'SleepWell Ergonomics disputed recovery claim VR-2038 (₹16,499). Review counter-evidence.',
      type: 'danger',
      timestamp: '2026-10-06T16:05:00.000Z',
      read: true,
      roleTarget: 'Vendor Management',
      linkPage: 'vendor',
      linkId: 'VR-2038'
    },
    {
      id: 'NOTIF-104',
      title: 'SLA Breach Warning',
      message: 'Case RET-1042 (₹42,999 Smartphone) has 1 hour remaining in SLA window.',
      type: 'danger',
      timestamp: '2026-10-07T09:00:00.000Z',
      read: false,
      roleTarget: 'Returns Manager',
      linkPage: 'exceptions',
      linkId: 'RET-1042'
    },
    {
      id: 'NOTIF-105',
      title: 'Auto-Decision Execution Success',
      message: 'Case RET-1048 auto-approved by AI Engine (Confidence: 96%). Refund RF-2048 created.',
      type: 'success',
      timestamp: '2026-10-07T09:32:00.000Z',
      read: true,
      roleTarget: 'Customer Service',
      linkPage: 'cases',
      linkId: 'RET-1048'
    }
  ],

  activityLog: [
    {
      id: 'ACT-901',
      timestamp: '2026-10-07T11:20:00.000Z',
      user: 'Pooja Verma',
      role: 'Customer Service',
      action: 'Submitted Return & Triggered Exception',
      entity: 'Case',
      entityId: 'RET-1045',
      details: 'Created case for Rahul Kumar (₹14,999). AI flagged high value + damage exception.'
    },
    {
      id: 'ACT-902',
      timestamp: '2026-10-07T09:40:00.000Z',
      user: 'Rajesh Nair',
      role: 'Vendor Management',
      action: 'Raised Vendor Recovery Claim',
      entity: 'VendorClaim',
      entityId: 'VR-2041',
      details: 'Raised warranty chargeback ₹4,899 against Nova Appliances Ltd for Case RET-1048.'
    },
    {
      id: 'ACT-903',
      timestamp: '2026-10-07T09:32:00.000Z',
      user: 'AI Decision Engine',
      role: 'System',
      action: 'Auto-Approved Return',
      entity: 'Case',
      entityId: 'RET-1048',
      details: 'Auto-approved refund ₹4,899 for Priya Sharma (Within 30d window, Low risk score 8/100).'
    },
    {
      id: 'ACT-904',
      timestamp: '2026-10-07T08:00:00.000Z',
      user: 'Vikramaditya Sen',
      role: 'Returns Manager',
      action: 'Approved Refund Exception',
      entity: 'Case',
      entityId: 'RET-1031',
      details: 'Approved ₹16,499 mattress defect refund under vendor warranty protocol; routed to Finance.'
    },
    {
      id: 'ACT-905',
      timestamp: '2026-10-06T15:20:00.000Z',
      user: 'Gurpreet Singh',
      role: 'Warehouse',
      action: 'Completed Return Disposition',
      entity: 'Disposition',
      entityId: 'DSP-3035',
      details: 'Restocked Silk Kurta to Delhi NCR Hub active inventory bin A-08 (+1 saleable).'
    },
    {
      id: 'ACT-906',
      timestamp: '2026-10-06T11:00:00.000Z',
      user: 'Ananya Deshmukh',
      role: 'Finance',
      action: 'Approved Settlement Disbursement',
      entity: 'Refund',
      entityId: 'RF-2035',
      details: 'Authorized UPI settlement ₹3,499 for Neha Jain via Paytm Gateway.'
    }
  ]
};
